server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update     # creates / updates tables automatically
    show-sql: true
    properties:
      hibernate.format_sql: true
